version: "3"

services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    command: "bundle exec foreman start"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "3000"

  app:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    # volumes:
    #   - .:/frontend
    command: npm run start
    ports:
      - "3001"
    depends_on:
      - api
  
  www:
    image: "nginx:1.10.1"
    restart: always
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"
    links:
      - "app:app"
      - "api:api"
    container_name: rr_www
    depends_on:
      - api
      - app